### PR TITLE
Price issue

### PR DESCRIPTION
**Pull request by Danielhiversen**

### CODE REVIEW

**Comment by CrallH** [comment]
Hi! This change should maybe be marked as breaking change as it changes from tibbers "PriceLevel" to "PriceRatingLevel" many automate using the Norms/cheap/expensive/very expensive attributes, now we get low/normal/high.
Screenshot_20241107-210807

**Comment by ismarslomic** [comment]
Thanks for making me aware of this @CrallH! I agree that this is a breaking change and it broke my existing automations!

**Comment by Danielhiversen** [comment]
Ohh, I did not know it was two different price levels

**Comment by TylonHH** [comment]
So will this change be forever and I have to review all my automation wich are broken now?
Or will the PriceRating a second attribute next to the common price level?

**Comment by Danielhiversen** [comment]
I am not really sure what to do :/ 

I think we should either keep it or change it back. To have both seems unnecessary. 

https://github.com/home-assistant/core/issues/130113#issuecomment-2464790660

**Comment by 4homeassistant** [comment]
Hi @Danielhiversen , I'd suggest to revert back to PriceLevel in order to make existing automations working again. Else thousands of users have to rewrite their automations or scripts relying on these attributes. Especially since there are four PriceLevels but only three PriceRatingLevels.

**Comment by TylonHH** [comment]
Five price levels 😉

But I totally agree. Please revert to the original price levels instead of price rating

**Comment by d99pli** [comment]
Agree, please revert to 5 levels with EXPENSIVE  etc. Thanks for a good service by the way!

**Comment by niccolodevries** [comment]
Indeed, I would like to also suggest reverting to the 5 levels with EXPENSIVE etc.

**Comment by james-1987** [comment]
Please revert back! I really want to have the 5 level control back.

**Comment by mnorrsken** [comment]
I had to revert home assistant upgrade and I hope it will work. I lost both price level and the current price when upgrading and my house got a bit cold... Please revert if possible! 😬 However I appreciate your efforts!

**Comment by TylonHH** [comment]
If you dont wanna be dependet on a 3rd party you can use the API by your own. HA supports Rest API.

Try this:

Go to https://developer.tibber.com/explorer and log in. Load your personal token and paste on the left site this:
```
{
  viewer {
    homes {
      currentSubscription{
        priceInfo{
          today {
            startsAt
            level
            total
          }
          tomorrow {
            startsAt
            level
            total
          }
        }
      }
    }
  }
}
```


You should see something like
```
{
  "data": {
    "viewer": {
      "homes": [
        {
          "currentSubscription": {
            "priceInfo": {
              "today": [
                {
                  "startsAt": "2024-11-14T00:00:00.000+01:00",
                  "level": "CHEAP",
                  "total": 0.3035
                },
                {
                  "startsAt": "2024-11-14T01:00:00.000+01:00",
                  "level": "CHEAP",
                  "total": 0.3012
                },
                {
                  "startsAt": "2024-11-14T02:00:00.000+01:00",
                  "level": "CHEAP",
                  "total": 0.2967
                },
                {
                  "startsAt": "2024-11-14T03:00:00.000+01:00",
                  "level": "CHEAP",
                  "total": 0.2922
                },
                {
                  "startsAt": "2024-11-14T04:00:00.000+01:00",
                  "level": "CHEAP",
                  "total": 0.2912
                },
```
There are much more data to get there. See the API https://developer.tibber.com/docs

Within HA you use REST to get this by yourself.

in sensors yaml paste this
```
- platform: rest
  name: TibberPreisREST
  unique_id: "d8a8c541-your-own-generated-id-632e18a5a5d3"
  resource: https://api.tibber.com/v1-beta/gql
  method: POST
  payload: '{ "query": "{ viewer { homes { currentSubscription { priceInfo { today { startsAt level total } tomorrow { startsAt level total } current { total } } } } } }" }'
  json_attributes_path: "$.data.viewer.homes[0].currentSubscription.priceInfo"
  json_attributes:
    - today
    - tomorrow
    - current
  value_template: "{{ value_json.current.total | float }}"
  scan_interval: 3600
  headers:
    Authorization: oooooYOURAPIoooooo
    Content-Type: application/json
    User-Agent: REST
  unit_of_measurement: EUR/kWh
```


validate the YAML restart and chek for sensor.tibberpreisrest

**Comment by Danielhiversen** [comment]
It is also an option to make template sensor if you want the old price level sensor.
Then you tweak the sensor as you want.

```
template:
  - sensor:
      - name: Electricity Price Level
        unique_id: electricity_price_level
        state: >-
          {%- set price = float(states('sensor.electricity_price_infinity_8'), default=-10000) -%}
          {%- set avg_price = float(state_attr('sensor.electricity_price_infinity_8', 'avg_price'), default=0) -%}
          {% if price > -10000 %}
            {{- 'SUPER_CHEAP' if price <= avg_price*0.4 -}}
            {{- 'VERY_CHEAP' if price <= avg_price*0.5 and price > avg_price*0.4 -}}
            {{- 'CHEAP' if price > avg_price*0.5 and price <= avg_price*0.9 -}}
            {{- 'NORMAL' if price > avg_price*0.9 and price < avg_price*1.15 -}}
            {{- 'EXPENSIVE' if price >= avg_price*1.15 and price < avg_price*1.4 -}}
            {{- 'VERY_EXPENSIVE' if price >= avg_price*1.4 }}
          {%else%}
            unknown
          {%endif%}
 ```
          
          
https://github.com/home-assistant/core/issues/130113#issuecomment-2464639626

**Comment by james-1987** [comment]
What a band aid fix. Why not fix your messed up commit?

**Comment by Danielhiversen** [comment]
Any contribution is welcome.
I spend a lot of spare time maintaining this. I changed the query to get data easier to work with.
I did not know that two different types of price levels exist. So I am sorry that the breaking change was not informed.

**Comment by SirHackalot2000** [comment]
Appreciate the work and effort. Just want to add yet another vote for reverting the change. There are many automation's that are now not working.

**Comment by TylonHH** [comment]
https://github.com/Danielhiversen/pyTibber/commit/3ae59e63a1be6a77d2e84e02642d585646410361

**Comment by ptz0n** [comment]
Time to revert? 👍

**Comment by Danielhiversen** [comment]
> I see in your code some PriceRating instead of level. Is it more then just replace PriceRating with Level?

No, it is a different data format

**Comment by imist** [comment]
I like the granularity in PriceLevel. PriceRatingLevel is too coarse imho. Plus many of us have automations based on PriceLevel already. Why can’t we just revert the change and make everyone happy? 🤓

**Comment by mnorrsken** [comment]
Ok I reverted home assistant to last months version and it seens to work. I will wait until it is decided what will happen but I guess it is better to use nordpool data directly instead.14 nov. 2024 kl. 14:05 skrev Daniel Hjelseth Høyer ***@***.***>:﻿
It is not something I will prioritize.
Any contributions are welcome.
Remember that this commit was part of a bug fix in HA, so we can not just revert it.

**Comment by Danielhiversen** [comment]
>  I guess it is better to use nordpool data directly instead


Then you have 3 different alternatives to get the price levels.

**Comment by imist** [comment]
Yeah, let's all of us create custom solution to overcome this sudden breaking change. Really smart!
What happened to backward compatibility??

**Comment by Danielhiversen** [comment]
As I have said anyone can contribute, and all contributions are welcome.
I will close this thread now.

**Pull request merged**
