### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by GunnarBjoru**
Replace ambiguous if sentence with two if-sentences.

### CODE REVIEW

**Comment by Danielhiversen** [comment]
Replaced with parentheses: 

https://github.com/Danielhiversen/pyTibber/commit/6c99a3356d3c237dc9d59ae19bb39868e558c8b7

**Comment by GunnarBjoru** [comment]
Thank you. Works fine now.

**Comment by GunnarBjoru** [comment]
Seems like I was a bit early to say it worked well. After midnight the price dropped again.

**Comment by Danielhiversen** [comment]
What version of pyTibber are you using?
0.13.7 ?

**Comment by GunnarBjoru** [comment]
Sorry, I was not using 0.13.7. I am sure it will work when using 0.13.7.

**Pull request closed without merging**
