### PR TITLE
Historic data by date

### PR DESCRIPTION
**Pull request by bison--**
This is my first real open source contribution, so sorry for any mistakes here ^^" (open for critique).

Purpose of the `get_historic_data_date` is to actually get data for a month without filtering through obscure "number of results".  

I also added a test for the new function.

Examples:
```python
first_day_of_month = datetime.now().replace(day=1)
data = await home.get_historic_data_date(first_day_of_month, 0, const.RESOLUTION_DAILY)
```

```python
first_day_of_month = datetime(2024, 8, 1)
data = await home.get_historic_data_date(first_day_of_month, 0, const.RESOLUTION_DAILY)
```

Note 1:  
The `Tibber.home.get_historic_data_date` resolution parameter could be hard set to daily, but I wanted to keep the current function styles.

Note 2:  
The `HISTORIC_DATA_DATE` need some of the other parameters for power generation.

Note 3:  
The query field `totalCost` is deprecated.  
Warning from the Api Explorer: `The field Consumption.totalCost is deprecated. use cost instead.`

Note 4:  
At first I created a monkeypatch and thought I could also contribute this to the main project, it may help someone in the future.

### CODE REVIEW

**Comment by bison--** [comment]
Updated the code to fix the failed checks.

**Comment by bison--** [comment]
Updated the code to fix the failed checks, again.

**Comment by bison--** [comment]
Updated the code to fix the failed checks, last time ^^.

**Comment by bison--** [comment]
it fails now at `test/test_tibber.py::test_tibber_invalid_token`, I haven't touched that ^^"

**Review by Danielhiversen — APPROVED** [review]
Thanks 👍

**Pull request merged**
