### PR TITLE
Add logging tests and adjust websocket logging level in Tibber integration

### PR DESCRIPTION
**Pull request by benganellison**
The test is flaky since it seems like all tests actually connects to tibber for the testing. I never written a mockup of a ws interface so i didn't really know how to address this.

### CODE REVIEW

**Comment by benganellison** [comment]
do you have any input to how to address the testing for this?

**Comment by Danielhiversen** [comment]
Fixing the linter is good enough

**Comment by benganellison** [comment]
Didn’t run ruff , though the pre-comit hook would. Will fix later today

**Comment by Danielhiversen** [comment]
Thanks 👍

**Pull request merged**
