### PR TITLE
Fetch consumption data 1

### PR DESCRIPTION
**Pull request by Danielhiversen**

### CODE REVIEW

**Comment by seagri** [comment]
Hi
Will this give hourly consumption though the tibber API? Without the Tibber Pulse or Watty

**Comment by Danielhiversen** [comment]
That has been available for years: https://github.com/Danielhiversen/pyTibber/blob/9763d702bb790539937a7c2b9720370ddfdf592b/tibber/__init__.py#L739

**Comment by Danielhiversen** [comment]
This pr is for homes with realtime meter

**Comment by seagri** [comment]
> That has been available for years:
> 
> https://github.com/Danielhiversen/pyTibber/blob/9763d702bb790539937a7c2b9720370ddfdf592b/tibber/__init__.py#L739

I see. I'm using Home assistant and wondering why I couldn't see that information as a sensor and thought that it was missing in this lib. but probably that code is missing in HA then.

**Comment by Danielhiversen** [comment]
@seagri In next release of HA you will get statistics with consumption a cost if do not have a realtime meter
https://deploy-preview-21092--home-assistant-docs.netlify.app/integrations/tibber/

**Pull request merged**
